apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-java-app
  template:
    metadata:
      labels:
        app: test-java-app
    spec:
      containers:
        - name: test-java-app
          image: docker.io/kavitamil13/test-java-app:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
