apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-java-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /test_app
        pathType: Prefix
        backend:
          service:
            name: test-java-app-service
            port:
              number: 80
